### ISSUE TITLE
Install Majave 10.14.3

### ISSUE THREAD

**Issue by li3p** [irelandKen/OptiPlex-7040-Clover-EFI#4]
Hi, thank you for your work . Have you tried install 10.14.3 on Dell Optiplex 7040 with a 4K Display monitor ? By using your EFI Folder I encountered the blank screen. Any idea to solve this ?

**Comment by irelandKen** [comment]
If no display with 1080p or 4K after system startup but before login, you need to use another DP port , in my case , just one DP port work.
