### ISSUE TITLE
Stuck on ++and black screen

### ISSUE THREAD

**Issue by jrway** [irelandKen/OptiPlex-7040-Clover-EFI#5]
Wanna say thank you first for this patch method for optiplex 7040. I've tried the BIOS modify method, but failed. So I use this patch method, but it stuck on black or ++. both in 10.14, 10.14.2. I try google this, seems the clover in you file is not up to date as the 10.14 or 10.14.2 required.(Not sure). It's a bit hard for me to hackintosh this machine. Still working on it.

**Comment by irelandKen** [comment]
Hey gay

I write a "DVMT fix step" for you, just have a look. 

Waiting for your good news.

**Comment by irelandKen** [comment]
Try to use this branch `https://github.com/irelandKen/DELL-OptiPlex-7040-Clover/tree/macOS_10.14.2_WhateverGreen`.

Waiting for your test.

**Comment by ONEokDAMON** [comment]
Hey,
同样这款主机, 也是遇到了同样的问题, 1. 我下载黑果小兵的10.14.2 with clover的镜像, 然后删除了整个EFI, 替换成您的EFI

**Comment by irelandKen** [comment]
Hi ONE: 
    卡+++的话，除了config和kext，你需要替换drivers64UEFI整个目录。
    由于后面换了一台机器，7040的Clover就一直没更新了，或者我可以简单更新个10.14.4的让你试试。

**Comment by irelandKen** [comment]
Hey jrway:
    I just make support for 10.14.4, but not tested, can you help me to test it?
